version: "3"

services:
  server:
    image: public.ecr.aws/i2t4w1a3/skill-shuffle:server
    container_name: server
    ports:
      - "8080:8080"

  client:
    image: public.ecr.aws/i2t4w1a3/skill-shuffle:client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server

  proxy:
    image: public.ecr.aws/i2t4w1a3/skill-shuffle:proxy
    container_name: proxy
    restart: always
    ports:
      - "80:80"
