version: "3"

services:
  server:
    image: public.ecr.aws/i2t4w1a3/skill-shuffle:server
    # build: ./server
    container_name: server
    env_file:
      - ./server/.env
    ports:
      - "8080:8080"
    restart: always

  client:
    image: public.ecr.aws/i2t4w1a3/skill-shuffle:client
    # build: ./client
    container_name: client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server

  proxy:
    build: ./nginx
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme_challenge:/tmp/acme_challenge
