version: "3"

services:
  server:
    # image: public.ecr.aws/i2t4w1a3/skill-shuffle:server
    build: ./server
    container_name: server
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - database
    networks:
      - app-network

  database:
    # image: public.ecr.aws/i2t4w1a3/skill-shuffle:database
    image: mariadb
    container_name: database
    volumes:
      - ./database/skill_shuffle.sql:/docker-entrypoint-initdb.d/skill_shuffle.sql
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      - app-network

  client:
    # image: public.ecr.aws/i2t4w1a3/skill-shuffle:client
    build: ./client
    container_name: client
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

  proxy:
    build: ./nginx
    container_name: proxy
    restart: always
    environment:
      - ADMIN_PATH=${ADMIN_PATH}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/acme_challenge:/tmp/acme_challenge
    depends_on:
      - server
      - client
      - phpmyadmin
    networks:
      - app-network

  phpmyadmin:
    build: ./phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
